applicationConfig:
  tickPeriodMillis: 1000


consoleConfig:
  cellCharCount: 4


islandConfig:
  rows: 10
  columns: 10

  population:
    Wolf: 30
    Goat: 140
    Grass: 200
    Caterpillar: 1000

  cellCapacity:
    Wolf: 30
    Goat: 140
    Grass: 200
    Caterpillar: 1000


globalOrganismConfig:
  starvation: 25 # as a percentage of complete saturation per tick
  weightLoss: 25 # as a percentage of max weight per tick
  dissolution: 5 # a number of ticks


organisms:
  Wolf:
    icon: ğŸº
    maxWeight: 50
    maxSpeed: 3
    completeSaturation: 8 # kilograms
    preys:
      Goat: 60 # chance to catch a prey in percent

  Goat:
    icon: ğŸ
    maxWeight: 60
    maxSpeed: 3
    completeSaturation: 10
    preys:
      Grass: 100

  Grass:
    icon: ğŸŒ±
    maxWeight: 1
    maxSpeed: 0
    completeSaturation: 0
    preys:

  Caterpillar:
    icon: ğŸ›
    maxWeight: 0.01
    maxSpeed: 0
    completeSaturation: 0
    preys:
      Grass: 100