applicationConfig:
  tickPeriodMillis: 100


consoleConfig:
  cellIconCount: 4


windowConfig:
  width: 1400
  height: 800
  cellIconCount: 4


islandConfig:
  rows: 100
  columns: 20

  population:
    Wolf: 100
    Boa: 100
    Fox: 100
    Bear: 100
    Eagle: 100
    Horse: 100
    Deer: 200
    Rabbit: 100
    Mouse: 100
    Goat: 100
    Sheep: 100
    Boar: 100
    Buffalo: 100
    Duck: 100
    Grass: 400000
    Caterpillar: 10

  cellCapacity:
    Wolf: 30
    Boa: 30
    Fox: 30
    Bear: 5
    Eagle: 20
    Horse: 20
    Deer: 20
    Rabbit: 150
    Mouse: 500
    Goat: 140
    Sheep: 140
    Boar: 50
    Buffalo: 10
    Duck: 200
    Grass: 200
    Caterpillar: 1000


globalOrganismConfig:
  starvation: 25 # as a percentage of complete saturation per tick
  weightLoss: 25 # as a percentage of max weight per tick
  dissolution: 5 # a number of ticks


organisms:
  Wolf:
    icon: ğŸº
    maxWeight: 50
    maxSpeed: 3
    completeSaturation: 8 # kilograms
    preys:
      Horse: 10 # chance to catch a prey in percent
      Deer: 15
      Rabbit: 60
      Mouse: 80
      Goat: 60
      Sheep: 70
      Boar: 15
      Buffalo: 10
      Duck: 40

  Boa:
    icon: ğŸ
    maxWeight: 15
    maxSpeed: 1
    completeSaturation: 3
    preys:
      Fox: 15
      Rabbit: 20
      Mouse: 40
      Duck: 10

  Fox:
    icon: ğŸ¦Š
    maxWeight: 8
    maxSpeed: 2
    completeSaturation: 2
    preys:
      Rabbit: 70
      Mouse: 90
      Duck: 60
      Caterpillar: 40

  Bear:
    icon: ğŸ»
    maxWeight: 500
    maxSpeed: 2
    completeSaturation: 80
    preys:
      Boa: 80
      Horse: 40
      Deer: 80
      Rabbit: 80
      Mouse: 90
      Goat: 70
      Sheep: 70
      Boar: 50
      Buffalo: 20
      Duck: 10

  Eagle:
    icon: ğŸ¦…
    maxWeight: 6
    maxSpeed: 3
    completeSaturation: 1
    preys:
      Fox: 10
      Rabbit: 90
      Mouse: 90
      Duck: 80

  Horse:
    icon: ğŸ
    maxWeight: 400
    maxSpeed: 4
    completeSaturation: 60
    preys:
      Grass: 100

  Deer:
    icon: ğŸ¦Œ
    maxWeight: 300
    maxSpeed: 4
    completeSaturation: 50
    preys:
      Grass: 100

  Rabbit:
    icon: ğŸ‡
    maxWeight: 2
    maxSpeed: 2
    completeSaturation: 0.45
    preys:
      Grass: 100

  Mouse:
    icon: ğŸ
    maxWeight: 0.05
    maxSpeed: 1
    completeSaturation: 0.01
    preys:
      Caterpillar: 90
      Grass: 100

  Goat:
    icon: ğŸ
    maxWeight: 60
    maxSpeed: 3
    completeSaturation: 10
    preys:
      Grass: 100

  Sheep:
    icon: ğŸ‘
    maxWeight: 70
    maxSpeed: 3
    completeSaturation: 15
    preys:
      Grass: 100

  Boar:
    icon: ğŸ—
    maxWeight: 400
    maxSpeed: 2
    completeSaturation: 50
    preys:
      Mouse: 50
      Caterpillar: 90
      Grass: 100

  Buffalo:
    icon: ğŸƒ
    maxWeight: 700
    maxSpeed: 3
    completeSaturation: 100
    preys:
      Grass: 100

  Duck:
    icon: ğŸ¦†
    maxWeight: 1
    maxSpeed: 4
    completeSaturation: 0.15
    preys:
      Caterpillar: 90
      Grass: 100

  Caterpillar:
    icon: ğŸ›
    maxWeight: 0.01
    maxSpeed: 0
    completeSaturation: 0
    preys:
      Grass: 100

  Grass:
    icon: ğŸŒ±
    maxWeight: 1
    maxSpeed: 0
    completeSaturation: 0
    preys: